module.exports = {
  content: ["./public/index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      keyframes: {
        shake: {
          '0%': { transform: 'translate(0,0)' },
          '10%': { transform: 'translate(0,-5px)' },
          '20%': { transform: 'translate(0,0)' },
          '30%': { transform: 'translate(0,5px)' },
          '40%': { transform: 'translate(0,0)' },
          '50%': { transform: 'translate(0,-5px)' },
          '60%': { transform: 'translate(0,0)' },
          '70%': { transform: 'translate(0,5px)' },
          '80%': { transform: 'translate(0,0)' },
          '90%': { transform: 'translate(0,-5px)' },
          '100%': { transform: 'translate(0,0)' },
        }
      },
      animation: {
        'bounce-once': 'bounce 1s linear',
        'shaking': 'shake 0.3s linear'
      },
      aspectRatio: {
        "3/2": "3 / 2",
      },
      backgroundImage: {
        "arcade-background": "url('../assets/images/arcade/background.png')",
        "bank-background": "url('../assets/images/bank/background.png')",
        "fanghaus-background": "url('../assets/images/fanghaus/background.png')",
        "fanghaus-bench": "url('../assets/images/fanghaus/bench.png')",
        "main-street-background": "url('../assets/images/main-street/background.png')",
        "main-street-road": "url('../assets/images/main-street/road.png')",
        "wldfngz-background": "url('../assets/images/wldfngz/background.png')",
      },
      backgroundSize: {
        tiling: "auto 100%",
      },
      borderRadius: {
        xl: "25px",
        xxl: "35px",
      },
      boxShadow: {
        nfc: "-10px 8px 1px rgba(0, 0, 0, 0.1)",
      },
      borderWidth: {
        6: "6px",
      },
      colors: {
        "black": "#262022",
        "primary": "#6950d0",
        "secondary": "#614BBE",
        "cyan-dark": "#75b1aa",
        "cyan-darker": "#54807b",
        "cyan-light": "#94eee5",
        "gray-dark": "#aaa7b0",
        "gray-light": "#605e63",
        "green-dark": "#9ddeb2",
        "green-darker": "#5a7f66",
        "green-light": "#b7f4a0",
        "magenta-dark": "#a66cb0",
        "magenta-darker": "#784e7f",
        "magenta-light": "#e094ee",
        "purple-darkest": "#483692",
        "purple-darker": "#5d4e7f",
        "purple-dark": "#816db0",
        "purple-light": "#a994ee",
        "purple-lightest": "#bbacee",
        "red-dark": "#b06f7c",
        "red-darker": "#80515a",
        "red-light": "#ee94a3",
        "yellow-dark": "#b2b072",
        "yellow-darker": "#807e52",
        "yellow-light": "#eeeb9f",
        "white": "#fff",
        "window-bg": "#614BBE",
        "content-bg": "#8367F9",
        "primary-btn": "#FFC657",
        "secondary-btn": "#A572F7",
        "primary-btn-disabled": "#B9974F"
      },
      dropShadow: {
        standard: "0 6px 4px rgba(0, 0, 0, 0.25)",
        nfc: "-6px 4px 0px rgba(0, 0, 0, 0.1)",
      },
      fontFamily: {
        sans: ["Ubuntu", "ui-sans-serif", "system-ui"],
        mono: [
          "The Impostor",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "Liberation Mono",
          "Courier New",
          "monospace",
        ],
      },
      fontSize: {
        xxs: "0.6rem",
      },
      maxHeight: {
        200: "50rem",
        300: "75rem",
        400: "100rem",
      },
      minHeight: {
        100: "100px",
        125: "125px",
        150: "150px",
        175: "175px",
        200: "200px",
      },
      minWidth: {
        screen: "100vw",
      },
      spacing: {
        p1: "1%",
        p2: "2%",
        p3: "3%",
        p4: "4%",
        p5: "5%",
        p10: "10%",
        p15: "15%",
        p20: "20%",
        p25: "25%",
        p30: "30%",
        p40: "40%",
        p50: "50%",
      },
      textShadow: {
        "nfc": "-4px 3px 1px rgba(0, 0, 0, 0.1)",
        "nfc-light": "-3px 2px 1px rgba(0, 0, 0, 0.1)",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("tailwindcss-textshadow"),require('@tailwindcss/line-clamp')],
};
